spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://localhost/employee-service
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 8080