spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://localhost/employee-service
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      default: http://localhost:8761

server:
  port: 0