spring:
  application:
    name: address-service
  datasource:
    url: jdbc:mysql://localhost/address-service
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    me.approximations.microservices: debug

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      default: http://localhost:8761

server:
  port: 0