spring:
  application:
    name: address-service
  datasource:
    url: jdbc:mysql://localhost/address-service
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      default: http://localhost:8761

server:
  port: 8081